"""Add newsDate field to SponsorNews

Revision ID: 91e2ccd08922
Revises: f56255b55bce
Create Date: 2025-09-23 10:00:24.121935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e2ccd08922'
down_revision = 'f56255b55bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorNews', sa.Column('newsDate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorNews', 'newsDate')
    # ### end Alembic commands ###
