"""Add election models

Revision ID: b300460f8ead
Revises: 91e2ccd08922
Create Date: 2026-03-04 09:47:35.646898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b300460f8ead'
down_revision = '91e2ccd08922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electionCandidates',
    sa.Column('candidateID', sa.Integer(), nullable=False),
    sa.Column('categorySlug', sa.String(length=64), nullable=True),
    sa.Column('categoryName', sa.String(length=128), nullable=True),
    sa.Column('positionTitle', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('manifestoLink', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('candidateID')
    )
    op.create_table('electionSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isOpen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electionVotes',
    sa.Column('voteID', sa.Integer(), nullable=False),
    sa.Column('voterStudentID', sa.Integer(), nullable=False),
    sa.Column('candidateID', sa.Integer(), nullable=False),
    sa.Column('positionTitle', sa.String(length=128), nullable=True),
    sa.Column('categorySlug', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('submittedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('voteID'),
    sa.UniqueConstraint('voterStudentID', 'candidateID', name='uq_voter_candidate'),
    sa.UniqueConstraint('voterStudentID', 'positionTitle', 'rank', name='uq_voter_position_rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electionVotes')
    op.drop_table('electionSettings')
    op.drop_table('electionCandidates')
    # ### end Alembic commands ###
