"""Initial migration for SQLite

Revision ID: f56255b55bce
Revises: 
Create Date: 2025-09-14 10:28:14.381056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56255b55bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogPosts',
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('postTitle', sa.String(length=128), nullable=True),
    sa.Column('postDescription', sa.String(length=256), nullable=True),
    sa.Column('postTags', sa.String(length=256), nullable=True),
    sa.Column('postCreationDate', sa.Date(), nullable=True),
    sa.Column('postContent', sa.Text(), nullable=True),
    sa.Column('postAuthor', sa.String(length=256), nullable=True),
    sa.Column('postImageURL', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('postID')
    )
    op.create_table('execMembers',
    sa.Column('execID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('course', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.String(length=612), nullable=True),
    sa.Column('nationality', sa.String(length=128), nullable=True),
    sa.Column('pronouns', sa.String(length=32), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('liLink', sa.String(length=512), nullable=True),
    sa.Column('ghLink', sa.String(length=512), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('imageLink', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('execID')
    )
    op.create_table('sponsorNews',
    sa.Column('newsID', sa.Integer(), nullable=False),
    sa.Column('sponsorID', sa.Integer(), nullable=True),
    sa.Column('newsTitle', sa.String(length=256), nullable=True),
    sa.Column('newsDescription', sa.String(length=1024), nullable=True),
    sa.Column('newsURL', sa.String(length=1024), nullable=True),
    sa.Column('newsImageName', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('newsID')
    )
    op.create_table('sponsors',
    sa.Column('sponsorID', sa.Integer(), nullable=False),
    sa.Column('sponsorName', sa.String(length=256), nullable=True),
    sa.Column('sponsorDescription', sa.String(length=1024), nullable=True),
    sa.Column('sponsorIndustry', sa.String(length=256), nullable=True),
    sa.Column('sponsorTier', sa.String(length=128), nullable=True),
    sa.Column('sponsorSiteURL', sa.String(length=512), nullable=True),
    sa.Column('sponsorImageName', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('sponsorID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsors')
    op.drop_table('sponsorNews')
    op.drop_table('execMembers')
    op.drop_table('blogPosts')
    # ### end Alembic commands ###
